### ISSUE TITLE
Continue implementation of Redux and ES6

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#180]
# This issue will be used to track the implementation of Redux across the components. While doing the implementation we will also be updating the components to use ES6. (Closing #133 in favor of this issue.)

This issue will be closed over several pull requests, updating one or a few components at a time. Its possible that some components do not need updated by the Redux implementation, so at a minimum they all will be updated to use ES6.

**Update:** also as part of this issue we should add comment where necessary.

List of components to update:
- [x] AppContainer (covered in #163)
- [x] DivisionHeader (#206)
- [x] EditReports (#216)
- [x] EditsContainer (#216)
- [x] EditsDetail (#216)
- [x] EditsDetailRow (#216)
- [x] EditsGrouped (#216)
- [x] EditsHeaderDescription (#216)
- [x] EditsMacro (#216)
- [x] ~~EditsQ029 (wyatt)~~ moved to quality
- [x] EditsQ595 (#216)
- [x] EditsSelector (#216)
- [x] HomeLink
- [x] index (covered in #163)
- [x] InstitutionContainer (probably covered in #163)
- [x] InstitutionStatus (probably covered in #163)
- [x] IRSReport (#211)
- [x] Multicheck (#216)
- [x] Progress
- [x] RefileWarning (#215)
- [x] Resubmit
- [x] Signature (#211)
- [x] SubmissionContainer
- [x] Summary (#213)
- [x] UploadForm
- [x] UserHeading (#206)
- [x] ValidationProgress
