### ISSUE TITLE
UX review list (ongoing)

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform-ui#423]
- [x] The yellow banner currently displays on the "no syntax or validity errors" page. 
![image](https://cloud.githubusercontent.com/assets/9752096/23802355/0c369fb8-0581-11e7-97fc-a1533d134789.png)
- [x] name for the summary page, see #484 
- [ ] dealing with lots of edits in general, then per page
- [x] ability to re-file, see #486
- [ ] sidenav with progress, see #472 
- [x] splitting pages, see #475 
- [x] fixed parts of the app (edits nav, warnings, others?), see #471 and #488 as examples
- [x] thoughts on the refile modal

**Comment by awolfe76** [comment]
Closing this one out. We have issues open for everything we're focused on at the moment.
