### ISSUE TITLE
Add some event tracking to Google Tag Manager

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#824]
It would be nice to track a few other things ...

- [x] when 'upload a new file' is clicked
- [x] when a new upload is triggered using the dropzone
- [x] verification (or removing verification) of quality and macro
- [x] when 'download edit report' is clicked
- [x] when 'download irs report' is clicked
- [ ] when 'history of your progress in this filing period' is clicked
- [x] when pagination is used
- [x] when signature checkbox
- [ ] submission button clicked (not sure if we need this one or not)

__Extra__
- [ ] in order to use GTM debugging tool for events we need to add `https://tagmanager.google.com` to [`nginx.tmpl`](https://github.com/cfpb/hmda-platform-ui/blob/b8e9c41ea28c258c53b3569981913b1af3dd11ae/nginx/nginx.tmpl#L26), the error now is
```
Refused to load the script 'https://tagmanager.google.com/debug' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' data: https://www.googletagmanager.com https://www.google-analytics.com".
```

@designlanguage @keileyo @wpears please add/remove from this list.
